/home/luyao/miniconda3/envs/ITPAL_luyao/lib/python3.7/site-packages/torch/autograd/__init__.py:199: UserWarning: Error detected in MulBackward0. Traceback of forward call that caused the error:
  File "/home/luyao/amortized_vi_trpl/GMM/GMM_model.py", line 214, in <module>
    train_model(model, target, n_epochs, batch_size, n_context, n_components, eps, alpha, optimizer, split)
  File "/home/luyao/amortized_vi_trpl/GMM/GMM_model.py", line 155, in train_model
    loss_j = gate_pred[:, j] * (log_model_j - log_target_j - auxiliary_loss + alpha * reg_loss)
  File "/home/luyao/miniconda3/envs/ITPAL_luyao/lib/python3.7/site-packages/torch/fx/traceback.py", line 57, in format_stack
    return traceback.format_stack()
 (Triggered internally at ../torch/csrc/autograd/python_anomaly_mode.cpp:114.)
  allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "/home/luyao/amortized_vi_trpl/GMM/GMM_model.py", line 214, in <module>
    train_model(model, target, n_epochs, batch_size, n_context, n_components, eps, alpha, optimizer, split)
  File "/home/luyao/amortized_vi_trpl/GMM/GMM_model.py", line 162, in train_model
    loss.backward()
  File "/home/luyao/miniconda3/envs/ITPAL_luyao/lib/python3.7/site-packages/torch/_tensor.py", line 489, in backward
    self, gradient, retain_graph, create_graph, inputs=inputs
  File "/home/luyao/miniconda3/envs/ITPAL_luyao/lib/python3.7/site-packages/torch/autograd/__init__.py", line 199, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
RuntimeError: Function 'MulBackward0' returned nan values in its 0th output.